Issue/165
BeAPI/beapi-frontend-framework pull request #172
Opened 2021-09-01 09:53 UTC by ecorica

Helpers d'affichage(Tech days #1) #165

Ajouter d'un Helpers
Méthodes ajoutées : 
- get_acf_link
- the_acf_link
- get_custom_link
- acf_custom_link
- the_text
- get_the_text
- the_image
- get_share_link
- the_share_link

Suppression du fichier Accessible_Menu_Walker

2021-09-02 15:06 UTC, Rahe requested changes

2021-09-02 15:06 UTC, Rahe commented on inc/Helpers/Formatting/Term.php
> +function get_terms_name( int $post_id, string $taxonomy ): array {
Créer une fonction `get_terms_field` avec post_id, taxonomy et me champs à recup. Ca permettra d'appuyer cette fonction dessus

2021-09-02 15:06 UTC, Rahe commented on inc/Helpers/Formatting/Term.php
> +function get_terms_list( array $attributes, array $settings = [] ): string {
A mon avis le postid et la taxonomie doivent être deux paramètres obligatoires, pas des attributs

2021-09-02 15:06 UTC, Rahe commented on inc/Helpers/Formatting/Term.php
> +	$attributes = apply_filters( 'bea_theme_framework_term_list_attributes', $attributes );
passer post_id et taxonomy aussi

2021-09-02 15:06 UTC, Rahe commented on inc/Helpers/Formatting/Term.php
> +	foreach ( $terms as $key => $term ) {
implode ici pour ne pas avoir à gérer la manière dont est fait le séparateur

2021-09-02 15:06 UTC, Rahe commented on inc/Helpers/Formatting/Term.php
> +	$settings = apply_filters( 'bea_theme_framework_term_list_settings', $settings );
Plus de contexte

2021-09-02 15:06 UTC, Rahe commented on inc/Helpers/Formatting/Term.php
> +			'items'     => '<li>%s</li>',
la gestion du before/after n'est pas le même que sur les autres fonctons, je pense que ça doit être unifié

2021-09-02 15:06 UTC, Rahe commented on inc/Helpers/Formatting/Term.php
> +			'separator' => '',
le séparateur c'est rien ? même pas un espace ?

2021-09-02 15:06 UTC, Rahe commented on inc/Helpers/Formatting/Text.php
> +	$settings = apply_filters( 'bea_theme_framework_get_text_settings', $settings );
Plus de contexte

2021-09-02 15:06 UTC, Rahe commented on inc/Helpers/Formatting/Text.php
> +	$value    = apply_filters( 'bea_theme_framework_the_text', escape_content_value( $value, $settings['escape'] ) );
Plus de contexte

2021-09-02 15:42 UTC, asadowski10 commented on inc/Helpers/Formatting/Link.php
> +	// Set rel attribute if target is _blank
On pourrait virer cette partie, vu qu'à la fin on appelle get_custom_link qui elle même refait ce job là ?

2021-09-02 15:42 UTC, asadowski10 commented on inc/Helpers/Formatting/Term.php
> +	$count = 1;
J'ai pas du tout compris ce que vous cherchez à faire ici... et cette histoire de terms_length etc ? 
De la PHP doc ou autre pour expliquer ?

2021-09-02 15:42 UTC, asadowski10 commented on inc/Helpers/Formatting/Text.php
> + * @usage BEA\Theme\Framework\Helpers\Formatting\Text\the_text( 'text' => 'Lorem ipsum', 'esc' => 'html', [ 'before' => '<p>', 'after' => '</p>' ] );
Pas la bonne php doc

2021-09-02 15:42 UTC, asadowski10 commented on inc/Helpers/Formatting/Escape.php
> +function escape_content_value( string $value, string $escape ) {
Différence entre escape_attribute_value et escape_content_value ? c'est le même code applicatif... autant faire qu'une methode escape_data

2021-09-02 15:56 UTC, ecorica commented on inc/Helpers/Formatting/Escape.php
> +	return $escape( $value );
[EA] '$escape($value)' would make more sense here (it also faster).  message de phpstorm

2021-09-02 15:58 UTC, ecorica commented on inc/Helpers/Formatting/Escape.php
> +	return $escape( $value );
c'est pas plutôt `call_user_func` ?

2021-09-02 15:58 UTC, ecorica commented on inc/Helpers/Formatting/Escape.php
> +	return $escape( $value );
+ message phpstorm [EA] '$escape($value)' would make more sense here (it also faster).

2021-09-02 16:03 UTC, ecorica commented on inc/Helpers/Formatting/Term.php
> +			'separator' => '',
rien vu de ça

2021-09-02 16:04 UTC, ecorica commented on inc/Helpers/Formatting/Text.php
> +	$settings = apply_filters( 'bea_theme_framework_get_text_settings', $settings );
cad ? :)

2021-09-02 16:08 UTC, ecorica commented on inc/Helpers/Formatting/Link.php
> +	// Set rel attribute if target is _blank
oui :)

2021-09-02 16:21 UTC, Rahe commented on inc/Helpers/Formatting/Escape.php
> +	return $escape( $value );
Mais ça permet pas de passer un objet ou une fonction anonyme à mon avis, à tester.

2021-09-02 16:22 UTC, Rahe commented on inc/Helpers/Formatting/Text.php
> +	$settings = apply_filters( 'bea_theme_framework_get_text_settings', $settings );
paramètres en plus pour ton filtre

2021-09-02 16:22 UTC, Rahe commented on inc/Helpers/Formatting/Term.php
> +	$count = 1;
pour moi le implode qui devrait être là

2021-09-02 16:22 UTC, Rahe commented on inc/Helpers/Formatting/Escape.php
> +function escape_content_value( string $value, string $escape ) {
l'un par défaut esc_attr, l'autre par défaut esc_html ;)

2021-09-03 09:40 UTC, petitphp commented on inc/Helpers/Formatting/Escape.php
> +function escape_content_value( string $value, string $escape ) {
Pourquoi `escape_content_value` contient pas l'appel à `esc_html` du coup ?

2021-09-03 09:50 UTC, Rahe commented on inc/Helpers/Formatting/Escape.php
> +	return $escape( $value );
Il manque l'échappement par défaut (esc_attr) si la fonction n'xiste pas

2021-09-03 09:50 UTC, Rahe commented on inc/Helpers/Formatting/Escape.php
> +		return $value;
Il manque l'échappement par défaut (esc_html) si la fonction n'xiste pas

2021-09-03 10:04 UTC, petitphp commented on inc/Helpers/Formatting/Term.php
> +		$terms_str .= sprintf( $settings['items'], esc_html( $term ) );
Là on utilise `esc_html` et pas `escape_content_value` ?

2021-09-03 10:12 UTC, petitphp commented on inc/Helpers/Formatting/Share.php
> + * @usage BEA\Theme\Framework\Helpers\Formatting\Share\get_share_link( ['name' => facebook'], [ 'u' => 'https://...'] );
PHP Doc ne correspond pas

2021-09-03 10:18 UTC, petitphp commented on inc/Helpers/Formatting/Term.php
> + * @usage BEA\Theme\Framework\Helpers\Formatting\Term\get_terms_array( 0, 'news-type' );
Pas le bon PHP Doc

2021-09-03 10:21 UTC, petitphp commented on inc/Helpers/Formatting/Image.php
> +	echo get_the_image( $image_id, $attributes, $settings ); // phpcs:ignore
Ajouter `get_the_image` à la liste des fonctions safe dans le phpcs plutôt que d'ignorer le warning ?

2021-09-03 12:24 UTC, ecorica commented on inc/Helpers/Formatting/Escape.php
> +	return $escape( $value );
mais si le truc c'est un callable tu peux mettre par défaut $escape='esc_attr' @Rahe  ?

2021-09-03 13:03 UTC, ecorica commented on inc/Helpers/Formatting/Escape.php
> +	return $escape( $value );
parce que sinon l'args devient une `callable|string $escape` donc par défaut foutre une string je sais pas si c'est top

2021-09-03 13:06 UTC, ecorica commented on inc/Helpers/Formatting/Escape.php
> +		return $value;
justement à un moment j'utilise get_the_icon si je mets une échappement si la fonction n'existe pas il va escape mon svg et je veux pas

2021-11-12 16:56 UTC, ecorica commented on inc/Helpers/Formatting/Link.php
> +	$attributes_escape = [];
ok

2021-11-12 16:56 UTC, ecorica commented on inc/Helpers/Formatting/Term.php
> +function get_terms_list( array $attributes, array $settings = [] ): string {
done

2021-11-12 16:56 UTC, ecorica commented on inc/Helpers/Formatting/Term.php
> +
done

2021-11-16 17:00 UTC, asadowski10 commented on inc/Helpers/Formatting/Link.php
> +		$settings['new_window'] = ! empty( $settings['new_window'] ) ? $settings['new_window'] : '<span class="sr-only">' . esc_html__(
Ajouter un commentaier pour a11y

2021-11-16 17:18 UTC, asadowski10 approved these changes

2021-11-16 17:22 UTC, merged