styles : change visuallyhidden basic class to sr-only accessible class
BeAPI/beapi-frontend-framework pull request #181
Opened 2021-09-10 08:28 UTC by francoistibo

2021-09-10 08:31 UTC, firestar300 requested changes

2021-09-10 08:31 UTC, firestar300 commented on src/scss/abstract/_m-checkbox-custom.scss
> +        @extend .sr-only;
Peut être profiter pour en faire une (ou des) mixins plutôt que d'utiliser un `@extend`

2021-09-10 16:22 UTC, firestar300 requested changes

2021-09-10 16:22 UTC, firestar300 commented on src/scss/abstract/_m-sr-only.scss
> +@mixin sr-only() {
```scss
@mixin sr-only {
    position: absolute !important;
    width: 1px !important;
    height: 1px !important;
    padding: 0 !important;
    margin: -1px !important;
    overflow: hidden !important;
    clip: rect(1px, 1px, 1px, 1px) !important; /* 1 */
    clip-path: inset(50%) !important;  /* 2 */
    white-space: nowrap !important;            /* 3 */
    border: 0 !important;
}
```

OU

```scss
@mixin sr-only($focusable: false) {
    @if $focusable {
        width: auto !important;
        height: auto !important;
        margin: auto !important;
        overflow: visible !important;
        clip: auto !important;
        clip-path: none !important;
        white-space: normal !important;
    } @else {
        width: 1px !important;
        height: 1px !important;
        padding: 0 !important;
        margin: -1px !important;
        overflow: hidden !important;
        clip: rect(1px, 1px, 1px, 1px) !important; /* 1 */
        clip-path: inset(50%) !important;  /* 2 */
        white-space: nowrap !important;            /* 3 */
        border: 0 !important;
    }
}

.sr-only {
    @include .sr-only;
}

.sr-only-focusable {
    @include .sr-only(true);
}
```

2021-09-13 07:29 UTC, francoistibo commented on src/scss/abstract/_m-sr-only.scss
> +@mixin sr-only() {
done. j'ai remis le :focus et :active sur le focusable.

2021-09-13 07:30 UTC, francoistibo commented
@firestar300 : resolved.

2021-09-13 13:39 UTC, firestar300 approved these changes

2021-09-14 12:49 UTC, firestar300 requested changes

2021-09-14 12:49 UTC, firestar300 commented on src/scss/abstract/_m-checkbox-custom.scss
> +        @include .sr-only;
```scss
@include sr-only;
```

2021-09-14 12:49 UTC, firestar300 commented on src/scss/abstract/_m-sr-only.scss
> +    @include .sr-only;
```scss
@include sr-only;
```

2021-09-14 12:49 UTC, firestar300 commented on src/scss/abstract/_m-sr-only.scss
> +    @include .sr-only(true);
```scss
@include sr-only(true);
```

2021-09-17 08:32 UTC, firestar300 approved these changes

2021-09-17 08:37 UTC, merged