Feature/core blocks ready
BeAPI/beapi-frontend-framework pull request #186
Opened 2021-11-03 09:15 UTC by firestar300

Cette Pull Request est pour le moment en draft. L'idée est ici qu'on discute ensemble de la réorganisation du dossier `scss` pour qu'il soit plus compatible avec Gutenberg et WordPress.

On constate plusieurs problèmes actuellement : 

- On ne se sert pas de tout ce qui est dans le BFF (ex : _message.scss, qui l'utilise ?)
- Il y'a beaucoup d'effets de bords entre le style déclaré à l'extérieur des. composants Gutenberg et à l'intérieur
- La gestion des alignwide et alignfull n'est pas optimale
- Et il y'a surement d'autres soucis auquel je n'ai pas pensé mais j'ai voulu rajouté un point pour gonfler le nombre de lignes 😏

Voici ce que je propose dans cette PR : 
- Garder le meilleur de ce qu'on propose. Je pense que le point fort, ce sont les mixins qu'on utilise souvent (en tout cas pour ma part même si je n'utilise pas tout).
- S'inspirer de ce que font les autres thèmes WordPress. J'ai regardé comment [TwentyTwentyOne](https://github.com/WordPress/twentytwentyone/tree/ba9f20cad89163761185c0467b346ba42541ae22/assets/sass) organisait des dossiers et fichiers et je m'en suis fortement inspiré pour cette PR.

Pour ma part, je vais adopter cette nouvelle réorganisation sur un nouveau projet et incrémenter cette PR au fur et à mesure.

Au plaisir d'en discuter avec vous.

2021-11-03 22:02 UTC, Rahe commented on page.php
> +<?php get_header();
Pk ajouter ce fichier ? Le fichier index.php devrait faire le fallback complet

2021-11-08 15:59 UTC, firestar300 commented on page.php
> +<?php get_header();
C'était pour tester les composants, mais je peux le supprimer.

2022-03-18 11:55 UTC, francoistibo commented
### Réunion du 18.03.22 - TODO

- bouger _fonts.scss de 01-abstract vers 03-base (car génère du CSS donc ne doit pas etre dans abstract)
- passer par les variables css pour gérer les breakpoints (ex : base-spacing, font-size, largeurs container wp, ). cf : https://github.com/BeAPI/cd78-recrutement/blob/gutenberg/web/app/themes/cd78-recrutement/src/scss/abstract/_variables.scss 
- mixer les solutions milan / nicoL pour la taille des containers/layout
- pour le composant btn, utiliser les classes abstraites + les extend (n'apparait dans le CSS si pas utilisé). cf solution sur projet quanim-corpo
- améliorer la mixin title : remplacer le XL, L, M... par H1, H2, H3 (plus gutenberg friendly) + cf kiloutou espagne
- revoir l'utilisation abusive des variables CSS dans la PR : ne pas utiliser ce genre de variables pour configurer, mais seulement pour gérer des problématiques de responsive ou de variantes
- attention a ne pas dupliquer des imports de scss dans
- renommer tous les index.scss a la racine par le nom dans lequel il est : 05-blocks, le fichier index doit s'appeler blocks.scss (et blocks-editor.scss... on a rajoute '-editor' si fichier BO dédié). but : ne pas avoir plein de fichiers avec le meme nom
- voir si mise en place des classes utilitaires .row et classes justify utilisées par milan
- 
-

2022-05-30 21:00 UTC, Rahe commented on inc/Helpers/Menu_Walker.php
> +class Menu_Walker extends \Walker_Nav_Menu {
Quel est le but du Walker ?

2022-06-06 08:22 UTC, Rahe requested changes

2022-06-06 08:22 UTC, Rahe commented on components/blocks/header.php
> +				<span class="sr-only">Ouvrir/Fermer le menu</span>
Ca devrait être internationnalisé

2022-06-06 08:22 UTC, Rahe commented on components/blocks/footer.php
> +<footer id="footer" class="footer" role="contentinfo" aria-label="Pied de page">
Ca devrait être internationnalisé

2022-06-06 08:22 UTC, Rahe commented on components/blocks/header.php
> +				<strong>Un joli logo</strong>
Ca devrait être internationnalisé

2022-06-06 08:22 UTC, Rahe commented on components/blocks/skip-links.php
> +		<a href="#content">Contenu principal</a>
Ca devrait être internationnalisé

2022-06-06 08:22 UTC, Rahe commented on components/blocks/skip-links.php
> +		<a href="#footer">Pied de page</a>
Ca devrait être internationnalisé

2022-06-06 08:22 UTC, Rahe commented on src/js/editor.js
>  // Native Gutenberg
Attention, ici on fait beaucoup de retraits en JS.
Préciser quelque part ce que l'on fait, pourquou on le fait.
Attention au Lorem Ipsum...

2022-06-06 09:40 UTC, Rahe requested changes

2022-06-06 09:40 UTC, Rahe commented on components/blocks/footer.php
> +<footer id="footer" class="footer" role="contentinfo" aria-label="<?php _e( 'Footer', 'beapi-frontend-framework' ); ?>">
C'est un attribut, donc a échaper avec esc_attr_e

2022-06-06 09:40 UTC, Rahe commented on components/blocks/header.php
> +				<span class="sr-only"><?php _e( 'Open/Close the menu', 'beapi-frontend-framework' ); ?></span>
esc_html_e car c'est un contenu

2022-06-06 09:40 UTC, Rahe commented on components/blocks/header.php
> +<header id="header" class="header" role="banner" aria-label="Entête de page">
Pas traduit ici

2022-06-06 09:40 UTC, Rahe commented on components/blocks/header.php
> +			<nav id="menu" class="header__menu" aria-label="<?php _e( 'Main navigation', 'beapi-frontend-framework' ); ?>" role="navigation">
esc_Attr_e puisqu'un attribut

2022-06-06 09:40 UTC, Rahe commented on components/blocks/skip-links.php
> +<ul class="skip-links skip-links--hidden" aria-label="<?php _e( 'Fast access links', 'beapi-frontend-framework' ); ?>">
esc_Attr_e puisqu'un attribut

2022-06-06 09:40 UTC, Rahe commented on components/blocks/skip-links.php
> +		<a href="#content"><?php _e( 'Main content', 'beapi-frontend-framework' ); ?></a>
esc_html_e puisqu'un contenu

2022-06-06 09:40 UTC, Rahe commented on components/blocks/skip-links.php
> +		<a href="#footer"><?php _e( 'Footer', 'beapi-frontend-framework' ); ?></a>
esc_html_e puisqu'un contenu

2022-06-06 09:40 UTC, Rahe commented on header.php
> +	<main id="content" role="main" tabindex="-1" aria-label="<?php _e( 'Main content', 'beapi-frontend-framework' ); ?>">
esc_attr_e puisqu'un attribut

2022-06-06 09:40 UTC, Rahe commented on inc/Helpers/Menu_Walker.php
> +			$output .= '<button class="header__sub-menu-toggle" type="button"><span class="sr-only">' . __( 'Toggle menu', 'beapi-frontend-framework' ) . '</span>' . get_the_icon( 'down' ) . '</button>';
esc_html_e puisqu'un contenu

2022-06-06 09:40 UTC, Rahe commented on inc/Helpers/Menu_Walker.php
> +class Accessible_Menu_Walker extends \Walker_Nav_Menu {
A quoi sert ce walker ?

2022-06-06 09:40 UTC, Rahe commented on src/js/editor.js
>  // Native Gutenberg
Où comptez-vous documenter cette partie ou ce fichier ?

2022-06-06 10:17 UTC, francoistibo commented on inc/Helpers/Menu_Walker.php
> +class Accessible_Menu_Walker extends \Walker_Nav_Menu {
à préparer le terrain pour surcharger le menu WP en mode accessible (il ne l'est pas par défaut)

2022-06-06 10:23 UTC, francoistibo commented on inc/Helpers/Menu_Walker.php
> +class Accessible_Menu_Walker extends \Walker_Nav_Menu {
a rajouter le burger menu (accessible) de base, dont on se sert sur tous les projets

2022-06-06 11:02 UTC, francoistibo commented on inc/Helpers/Menu_Walker.php
> +class Menu_Walker extends \Walker_Nav_Menu {
- poser le bouton burger (accessible) pour le menu mobile (dont on se sert sur tous le sprojets
- poser la base pour la surcharge du menu WP en mode accessible (il ne l'est pas par défaut).

2022-06-06 11:04 UTC, francoistibo commented on src/js/editor.js
>  // Native Gutenberg
on va avoir besoin de merger ces modifs rapidement, mais je me note (carte notion theme dev) de traiter ce  commentaire.

2022-06-06 11:08 UTC, francoistibo approved these changes

2022-06-06 12:28 UTC, n-langle approved these changes

2022-06-06 12:30 UTC, Rahe approved these changes

2022-06-06 13:01 UTC, merged