feat php patterns with terms helper
BeAPI/beapi-frontend-framework pull request #216
Opened 2022-03-04 12:24 UTC by ptesei

2022-03-04 14:29 UTC, Rahe commented on inc/Helpers/Pattern_Content.php
> +	return sprintf(
@ptesei Il vaudrait mieux ici faire 
```php
$data = [ 'id' => absint( $term->term_id ), 'taxonomy' =>  esc_attr( $taxonomy )  ];
return wp_json_encode( $data );
```

2022-03-04 14:31 UTC, Rahe commented
L'approche de twentytwenty-two n'a pas été envisagée/retenue ?

2022-03-04 17:18 UTC, petitphp reviewed
Je ne vois pas la modification de la fonction `get_pattern_content` avec l'ajout du `ob_start` ?

2022-03-16 14:52 UTC, Rahe requested changes

2022-03-16 14:52 UTC, Rahe commented on assets/patterns/example.php
> +<!-- wp:beapi/dynamic-block {"postType":"post","perLine":3,"terms":<?php echo maybe_term( 'example', 'category' ); ?>,"displayMode":"grid"} /--></div>
A mettre dans le wiki en exemple, ça risque de devenir un fichier qui est dans tous les projets et reste là pour rien

2022-03-16 14:52 UTC, Rahe commented on inc/Helpers/Pattern_Content.php
> + * @usage Unaf\Master\Theme\Helpers\Pattern_Content\maybe_term( 'slug','taxonomy' );
UNAF n'a rien à faire ici

2022-03-16 14:52 UTC, Rahe commented on inc/Helpers/Pattern_Content.php
> +
UNAF n'a rien à faire ici

2022-04-12 09:40 UTC, Rahe commented on inc/Services/Editor_Patterns.php
> +		remove_theme_support( 'core-block-patterns' );
Pourquoi retirer les core pattern ? On perd aussi les catégories par défaut.
De plus ce n'est pas le bon filtre, pas `init` mais `after_setup_theme`.

2022-04-12 15:42 UTC, ptesei commented on inc/Services/Editor_Patterns.php
> +		remove_theme_support( 'core-block-patterns' );
1. on les a toujours viré. aussi on block les appelles vers l'extérieurs.
2. avec after_setup_theme ne marche pas

2022-04-26 16:28 UTC, Rahe requested changes

2022-04-26 16:28 UTC, Rahe commented on assets/patterns/media-text.php
> +return array(
replacer array par []

2022-04-26 16:28 UTC, Rahe commented on inc/Services/Editor_Patterns.php
> +		$pattern_categories = array(
PHP doc usage

2022-04-26 16:28 UTC, Rahe commented on inc/Services/Editor_Patterns.php
> +			if ( ! \WP_Block_Pattern_Categories_Registry::get_instance()->is_registered( $name ) ) {
short continue, si registered, continue

2022-04-26 16:28 UTC, Rahe commented on inc/Services/Editor_Patterns.php
> +			$pattern_file = get_theme_file_path( '/assets/patterns/' . $block_pattern . '.php' );
vérifier is_file pour éviter de require false

2022-04-26 16:28 UTC, Rahe commented on inc/Services/Editor_Patterns.php
> +				require $pattern_file
require_once

2022-04-26 16:28 UTC, Rahe commented on inc/Services/Editor_Patterns.php
> +				'project/' . $block_pattern,
"beapi-frontend-framework/"

2022-04-28 09:49 UTC, ptesei commented on inc/Services/Editor_Patterns.php
> +				require $pattern_file
phpstorm dit de laisser require

2022-05-02 08:56 UTC, Rahe requested changes

2022-05-02 15:40 UTC, ptesei commented on inc/Services/Editor_Patterns.php
> +		}
@Rahe donc je dois bouger ce test dehors?

2022-05-02 15:45 UTC, Rahe commented on inc/Services/Editor_Patterns.php
> +		}
Ah punaise je l'ai pas vu, non laisse le ici et je resolve le tout :)

2022-05-05 09:27 UTC, Rahe approved these changes

2022-05-05 09:55 UTC, merged