fix shared link accessibility
BeAPI/beapi-frontend-framework pull request #217
Opened 2022-03-04 12:41 UTC by ptesei

2022-03-11 14:33 UTC, asadowski10 approved these changes

2022-03-11 15:27 UTC, firestar300 requested changes

2022-03-11 15:27 UTC, firestar300 commented on inc/Helpers/Formatting/Share.php
> +use function Unaf\Master\Theme\Helpers\Svg\get_the_icon;
Not UNAF

2022-03-16 14:30 UTC, Rahe commented
@ptesei Tu peux détailler ici la différence de génération de HTML entre la version précédente et celle-ci ?

2022-03-16 14:36 UTC, ptesei commented
<span class="sr-only">Facebook</span>' ajoute un texte lisible par le lecteur d'écran  car les icones sont en aria hidden

2022-03-16 14:38 UTC, firestar300 approved these changes

2022-03-29 12:05 UTC, merged