Fix/helpers a11y
BeAPI/beapi-frontend-framework pull request #242
Opened 2022-06-16 13:14 UTC by ptesei

2022-06-21 14:38 UTC, Rahe requested changes

2022-06-21 14:38 UTC, Rahe commented on grumphp.yml
> +        - "beapi.top"
Non nécessaire, ce sont des environnements internes, gérés par le skeleton

2022-06-21 14:38 UTC, Rahe commented on grumphp.yml
> +      standard: ['phpcs.xml.dist']
Pas nécessaire de changer le nom

2022-06-21 14:38 UTC, Rahe commented on inc/Helpers/Formatting/Link.php
> +	if ( empty( $attributes['title'] ) ) {
Tu as array_filter pour retirer les entrées vides automatiquement.

2022-06-21 14:38 UTC, Rahe commented on phpcs.xml.dist
> +         name="WP Skeleton"
Ce n'est pas wp-skeleton à laisser tel quel

2022-06-24 11:08 UTC, Rahe commented on grumphp.yml
> +        - "beapi.top"
A supprimer

2022-06-24 11:08 UTC, Rahe commented on grumphp.yml
> +      standard: ['phpcs.xml.dist']
mettre le phpcs.xml comme précédemment

2022-06-24 11:10 UTC, Rahe commented on phpcs.xml.dist
> +    <exclude-pattern>autoload.php</exclude-pattern>
il n'y a pas de fichier autoload.php dans le thème.

2022-08-09 08:38 UTC, Rahe requested changes

2022-08-09 08:38 UTC, Rahe commented on inc/Helpers/Formatting/Link.php
> +	if ( empty($attributes['title'])) {
Les coding standards ne sont pas respectés ici

2022-08-09 08:38 UTC, Rahe commented on inc/Helpers/Formatting/Link.php
> +	if ( empty($attributes['target'])) {
Les coding standards ne sont pas respectés ici

2022-08-09 08:38 UTC, Rahe commented on phpcs.xml.dist
> -    <exclude-pattern>dist/</exclude-pattern>
Pourquoi le retirer ?

2022-08-09 08:38 UTC, Rahe commented on phpcs.xml.dist
> -    <exclude-pattern>src/</exclude-pattern>
Pourquoi le retirer ?

2022-08-09 08:38 UTC, Rahe commented on phpcs.xml.dist
> -    <exclude-pattern>scripts/</exclude-pattern>
Pourquoi le retirer ?

2022-08-09 08:38 UTC, Rahe commented on phpcs.xml.dist
> -    <rule ref="PHPCompatibility"/>
Pourquoi le retirer ?

2022-08-10 07:23 UTC, ptesei commented on phpcs.xml.dist
> -    <exclude-pattern>scripts/</exclude-pattern>
venor et script ne sont plus la , src et dist ne contient plus des fichiers php

2022-08-10 07:24 UTC, ptesei commented on phpcs.xml.dist
> -    <rule ref="PHPCompatibility"/>
cf https://github.com/BeAPI/wp-skeleton/blob/master/phpcs.xml.dist , j'ai simplement sync les deux

2022-08-10 07:25 UTC, Rahe commented on phpcs.xml.dist
> -    <exclude-pattern>scripts/</exclude-pattern>
Ca permet que phpcs n'aille pas scanner ces dossiers car on sait qu'ils ne portent pas de fihciers php, du coup on gagne en temps de génération.
vendor est présent dans ce repo quand fais composer install et que tu lances les commandes, tout doit être conservé

2022-08-10 07:27 UTC, Rahe commented on phpcs.xml.dist
> -    <rule ref="PHPCompatibility"/>
Il faut le conserver, faut considérer ce fichier comme étant absent lors de la création des thèmes et qu'il sert ici au dev  du thème en standalone.
Donc on veut checker la version de PHP et sa. compat, qu'il soit absent sur le skeleton n'est pas normal

2022-08-29 14:33 UTC, Rahe approved these changes

2022-08-29 14:38 UTC, merged