fix (paragraph): typo
BeAPI/beapi-frontend-framework pull request #266
Opened 2022-07-21 15:37 UTC by firestar300

2022-07-22 07:10 UTC, francoistibo approved these changes

2022-08-01 14:33 UTC, francoistibo requested changes

2022-08-01 14:33 UTC, francoistibo commented on src/scss/06-blocks/core/_paragraph.scss
> +    line-height: $line-height-base;
@firestar300 carrément supprimer le line-height

2022-08-04 08:09 UTC, francoistibo approved these changes

2022-08-22 10:25 UTC, ptesei approved these changes

2022-08-29 14:23 UTC, merged