fix (header) : handle admin-bar scroll attachment on mobile
BeAPI/beapi-frontend-framework pull request #309
Opened 2022-12-13 09:28 UTC by n-langle

2022-12-13 15:03 UTC, firestar300 requested changes

2022-12-13 15:03 UTC, firestar300 commented on .stylelintrc
> +                        "ingore": ["custom-properties"],
"ignore"

2022-12-19 14:47 UTC, francoistibo approved these changes

2022-12-19 14:48 UTC, firestar300 approved these changes

2022-12-19 14:48 UTC, merged