feat (mixins): improve hover mixin
BeAPI/beapi-frontend-framework pull request #310
Opened 2022-12-16 16:00 UTC by firestar300

## Add additional selectors parameter.

### Before
```scss
/**
 * Hover
 *
 *          Hover Active Focus pseudo selector mixin
 */

@mixin hover {
    &:hover,
    &:active,
    &:focus {
        @content;
    }
}

```

### Now
```scss
@use "sass:list";

/// Add active, focus and hover pseudo selectors to element
///
/// @param {list} $additionalSelectors
///   List of additional selectors
@mixin hover($additionalSelectors: ()) {
    $selectors: list.join(("&:hover", "&:active", "&:focus"), $additionalSelectors, comma);

    #{$selectors} {
        @content;
    }
}

```

### Usage

#### Input
```scss
    a {
        @include hover(("&#foo", "&.bar")) {
            color: $color-primary;
            background-color: $color-dark;
        }
    }
```

#### Output
```css
a:active,
a:focus,
a:hover,
a#foo,
a.bar {
    color: #ff0;
    background-color: #000;
}
```

2022-12-16 16:40 UTC, ptesei approved these changes

2022-12-19 08:29 UTC, n-langle requested changes

2022-12-19 08:29 UTC, n-langle commented on src/scss/02-tools/_m-hover.scss
> +/// @param {list} $additionalSelectors
Pourquoi une list plutôt qu'une string ? Ou les  deux si la list est nécessaire :
```
@mixin hover($additional-selectors: null) {
    $selectors: "&:hover, &:active, &:focus";

    @if ($additional-selectors) {
        @if (type-of($additional-selectors) == "string") {
            $selectors: $selectors "," $additional-selectors;
        }
        @else if (type-of($additional-selectors) == "list") {
            $selectors: list.join($selectors, $additional-selectors, comma);
        }
    }

    #{$selectors} {
        @content;
    }
}
```
```
@include hover("&.is-active, &.is-hover");
```

2022-12-19 14:49 UTC, n-langle submitted a review, later dismissed

2022-12-19 14:51 UTC, francoistibo approved these changes

2022-12-19 14:51 UTC, merged