fix (header) : handle escape keyup, add aria attributes
BeAPI/beapi-frontend-framework pull request #311
Opened 2022-12-21 08:57 UTC by n-langle

2022-12-21 08:59 UTC, Rahe commented on inc/Helpers/Custom_Menu_Walker.php
> +			$output .= '<button class="header__sub-menu-toggle" type="button" aria-expanded="false" aria-controls="header-sub-menu-' . self::$sub_menu_counter . '">';
$depth comporte cette information non ?

2022-12-21 09:02 UTC, n-langle commented on inc/Helpers/Custom_Menu_Walker.php
> +			$output .= '<button class="header__sub-menu-toggle" type="button" aria-expanded="false" aria-controls="header-sub-menu-' . self::$sub_menu_counter . '">';
$depth correspond au niveau du sous menu, donc $depth peut être commun à plusieurs sous menu. Il faut ici un numéro unique pour lier le bouton toggle

2022-12-21 09:10 UTC, n-langle commented on inc/Helpers/Custom_Menu_Walker.php
> +			$output .= '<button class="header__sub-menu-toggle" type="button" aria-expanded="false" aria-controls="header-sub-menu-' . self::$sub_menu_counter . '">';
c'est modifié

2022-12-21 09:15 UTC, Rahe submitted a review, later dismissed

2022-12-29 13:46 UTC, cedric07 approved these changes

2022-12-29 14:41 UTC, cedric07 requested changes

2022-12-29 14:41 UTC, cedric07 commented on inc/Helpers/Custom_Menu_Walker.php
> +			$output .= '<div id="header-sub-menu-' . $item->ID . '" class="header__sub-menu header__sub-menu-level-' . $depth . '"><div>';
Vu avec @ecorica il manque les escapes et aussi utiliser sprintf

2023-01-02 14:52 UTC, francoistibo commented on inc/Helpers/Custom_Menu_Walker.php
> +			$output .= '<div id="header-sub-menu-' . $item->ID . '" class="header__sub-menu header__sub-menu-level-' . $depth . '"><div>';
cf retours d'egidio sur une PR de SPF

2023-01-09 13:29 UTC, Rahe submitted a review, later dismissed

2023-01-16 15:01 UTC, ptesei approved these changes

2023-01-16 15:02 UTC, cedric07 approved these changes

2023-01-16 15:02 UTC, merged