feat (ari) add image with caption default template
BeAPI/beapi-frontend-framework pull request #314
Opened 2022-12-31 11:10 UTC by ptesei

enables `'data-caption' => true`

2023-01-02 09:50 UTC, cedric07 submitted a review, later dismissed

2023-01-02 10:27 UTC, n-langle requested changes

2023-01-02 10:27 UTC, n-langle commented on src/conf-img/tpl/default-picture-caption.tpl
> +    <figcaption>%%caption%%</figcaption>
La balise picture ne devrait pas avoir le figcaption comme enfant, seulement les balises img et source.

2023-01-02 15:05 UTC, francoistibo commented on src/conf-img/tpl/default-picture-caption.tpl
> +    <figcaption>%%caption%%</figcaption>
- supprimer les conditions IE9
- ajouter une figure
- sortir le figcaption de picture
- ajouter le figure sur le tpl par défaut aussi

2023-01-04 08:17 UTC, firestar300 requested changes

2023-01-04 08:17 UTC, firestar300 commented on src/conf-img/tpl/default-picture-caption.tpl
> +<figcaption>%%caption%%</figcaption>
Ajouter l'élément figure.

> L'élément HTML &lt;figcaption&gt; représente une légende décrivant le reste du contenu de son élément parent [&lt;figure&gt;](https://developer.mozilla.org/fr/docs/Web/HTML/Element/figure).

https://developer.mozilla.org/fr/docs/Web/HTML/Element/figcaption

```html
<figure>
  <noscript>
    %%data-location%%
    <img src="%%default_img%%" %%attributes%% />
  </noscript>
  <picture>
      %%sources%%
      <img %%srcgif%% %%attributes%%/>
  </picture>
  <figcaption>%%caption%%</figcaption>
</figure>
```

2023-01-16 15:07 UTC, francoistibo approved these changes

2023-01-16 15:08 UTC, cedric07 approved these changes

2023-01-30 15:04 UTC, francoistibo commented
- solution 1 : rajouter la balise <figure> une classe et en valeur une variable %class% + gérer la gestion par ARI
- solution 2 : laisser tel quel et prévoir de mettre la balise <figure> manuellement avec la ou les classe(s) que l'on souhaite avoir

2023-02-27 15:08 UTC, francoistibo commented on src/conf-img/tpl/default-picture-caption.tpl
> +<noscript>
du coup on rajoute figure et la classe souhaitée manuellement dans le tpl quand on en a besoin

2023-02-27 15:08 UTC, francoistibo commented on src/conf-img/tpl/default-picture-caption.tpl
> +<noscript>
poke @ptesei

2023-02-27 15:09 UTC, cedric07 approved these changes

2023-02-27 15:10 UTC, merged