mixin bg retina
BeAPI/beapi-frontend-framework pull request #332
Opened 2023-01-25 14:43 UTC by cedric07

Mixin image retina.
Utilisé sur SPF

2023-01-25 14:45 UTC, firestar300 requested changes

2023-01-25 14:45 UTC, firestar300 commented on src/scss/02-tools/_m-bg.scss
> +@mixin bg($filname, $retina: true, $position: center center, $size: auto 100%, $type: "png" ) {
`filename`

2023-01-25 14:45 UTC, firestar300 commented on src/scss/02-tools/_m-bg.scss
> +            background-image: url(../img/static/#{$filname}@2x.#{$type});
`filename`

2023-01-25 14:45 UTC, firestar300 commented on src/scss/02-tools/_m-bg.scss
> +    background-image: url(../img/static/#{$filname}.#{$type});
`filename`

2023-01-30 15:20 UTC, francoistibo requested changes

2023-01-30 15:20 UTC, francoistibo commented on src/scss/02-tools/_m-bg.scss
> +@mixin bg($filename, $retina: true, $position: center center, $size: auto 100%, $type: "png" ) {
remplacer le nom "background-static"
ajouter commentaire pour spécifier que ca n'est pas tès performant (en EN)

2023-01-30 15:21 UTC, francoistibo approved these changes

2023-01-30 15:21 UTC, ptesei approved these changes

2023-01-30 15:22 UTC, merged