remove text-align left on RTL
BeAPI/beapi-frontend-framework pull request #357
Opened 2023-06-08 14:37 UTC by cedric07

Supprime le text-align:left sur le body pour le RTL

2023-06-19 14:45 UTC, francoistibo requested changes
@cedric07 reprise de ce qui a été fait sur CMP en mode mixin

2023-06-19 14:55 UTC, cedric07 commented
> @cedric07 reprise de ce qui a été fait sur CMP en mode mixin

Done !

2023-06-21 09:23 UTC, firestar300 requested changes

2023-06-21 09:23 UTC, firestar300 commented on src/scss/02-tools/_m-rtl.scss
> +@mixin rtl() {
pas besoin de `()` si pas de paramètre.

2023-07-17 14:39 UTC, francoistibo approved these changes

2023-07-17 14:40 UTC, firestar300 approved these changes

2023-07-17 14:40 UTC, merged