feat (skip-links): set top value with --wp-admin--admin-bar--height
BeAPI/beapi-frontend-framework pull request #364
Opened 2023-08-07 15:22 UTC by firestar300

Pour information, la variable `--wp-admin--admin-bar--height` est fournie nativement par WordPress depuis `admin.css`.

2023-08-07 15:41 UTC, n-langle requested changes

2023-08-07 15:41 UTC, n-langle commented on src/scss/03-base/_variables-css.scss
> +        --wp-admin-bar-height: var(--wp-admin--admin-bar--height, 46px);
Cette déclaration n'est plus nécessaire, --wp-admin-bar-height sera égale à -wp-admin--admin-bar--height ou à 0 si elle n'est pas définie

2023-09-11 14:28 UTC, ptesei approved these changes

2023-09-11 14:28 UTC, cedric07 approved these changes

2023-09-11 14:29 UTC, n-langle approved these changes

2023-09-11 14:29 UTC, merged