feat (breadcrumb): add template part
BeAPI/beapi-frontend-framework pull request #377
Opened 2023-10-13 07:55 UTC by firestar300

2023-10-13 08:05 UTC, asadowski10 approved these changes

2023-10-13 08:07 UTC, cedric07 reviewed
Peut-être faire déjà l'appel au niveau du fichier header.php ?

```
<main id="content" role="main" tabindex="-1" aria-label="<?php esc_attr_e( 'Main content', 'yvelines-tourisme' ); ?>">
	<?php
	if ( ! is_front_page() && ! is_search() ) {
		get_template_part( 'components/parts/common/breadcrumb' );
	}
```

2023-10-13 08:13 UTC, asadowski10 approved these changes

2023-10-13 09:08 UTC, francoistibo requested changes

2023-10-13 09:08 UTC, francoistibo commented on components/parts/common/breadcrumb.php
> +<div class="breadcrumb-wrapper">
pour moi si on fait du BEM, ce serait plutôt class="breadcrumb" ici

2023-10-13 09:08 UTC, francoistibo commented on components/parts/common/breadcrumb.php
> +		<?php yoast_breadcrumb( '<div class="breadcrumb">', '</div>' ); ?>
et class="breadcrumb__inner" là

2023-10-13 09:36 UTC, francoistibo requested changes

2023-10-13 09:36 UTC, francoistibo commented on components/parts/common/breadcrumb.php
> +		<?php yoast_breadcrumb( '<div class="breadcrumb__inner">', '</div>' ); ?>
je ne sais plus ce que génère yoast mais au niveau markup html, y'a peut etre un `<nav class="breadcrumb" role="navigation" aria-label="<?php echo esc_attr( 'Breadcrumb' , 'beapi-frontend-framework'); ?>">...<nav>` à utiliser a la place de la première div

2023-10-13 12:53 UTC, francoistibo approved these changes

2023-10-23 15:05 UTC, francoistibo approved these changes

2023-10-23 15:05 UTC, merged