add lint task for grumphp npm script
BeAPI/beapi-frontend-framework pull request #379
Opened 2023-10-20 10:27 UTC by cedric07

Ajout des tâches lint pour les utiliser dans grumphp : https://github.com/phpro/grumphp/blob/v2.x/doc/tasks/npm_script.md

2023-10-20 10:27 UTC, firestar300 requested changes

2023-10-20 10:27 UTC, firestar300 commented on package.json
> +    "concurrently": "^8.2.2",
A mettre en devDependency plutôt.

2023-10-20 10:29 UTC, cedric07 commented on package.json
> +    "concurrently": "^8.2.2",
ah oui pardon merci

2023-10-20 11:40 UTC, francoistibo approved these changes

2023-10-23 14:52 UTC, francoistibo approved these changes

2023-10-23 14:53 UTC, firestar300 approved these changes

2023-10-23 14:53 UTC, merged