Less complex HTML markup
BeAPI/beapi-frontend-framework pull request #381
Opened 2023-10-27 16:30 UTC by francoistibo

2023-10-27 21:56 UTC, ptesei requested changes
je pense pas que soit un bonne idée cette pr :(

2023-10-30 07:41 UTC, francoistibo commented
> je pense pas que soit un bonne idée cette pr :(

pourquoi ?

2023-10-30 08:44 UTC, MarieComet approved these changes

2023-11-20 16:00 UTC, firestar300 approved these changes

2023-11-20 16:01 UTC, merged