fix missing svg file in dist folder after compilation
BeAPI/beapi-frontend-framework pull request #410
Opened 2024-05-29 14:42 UTC by cedric07

Les fichiers svg du dossier static n'étaient pas copiés dans le dossier dist.

2024-06-03 15:06 UTC, francoistibo requested changes

2024-06-03 15:06 UTC, francoistibo commented on src/js/post-build.js
> +requireAll(require.context('../img/static', true, /\.(png|jpe?g|gif|svg)$/))
rajouter avif et webp (+ à ajouter dans le loader ?)

2024-07-25 09:46 UTC, cedric07 commented on src/js/post-build.js
> +requireAll(require.context('../img/static', true, /\.(png|jpe?g|gif|svg)$/))
Done

2024-07-25 09:46 UTC, cedric07 commented
> rajouter avif et webp (+ à ajouter dans le loader ?)

Done

2024-09-09 14:58 UTC, merged